"""Dream router: dispatch classified items to the right files on disk.

Writes each item from the dream agent's output to the correct target:

  global_memory   → ~/.claude/somnium/memory/<date>-<slug>.md
  project_memory  → <repo>/.claude/somnium/memory/<date>-<slug>.md
  global_skill    → ~/.claude/skills/<slug>/SKILL.md
  project_skill   → <repo>/.claude/skills/<slug>/SKILL.md
  claude_md_patch → append to <repo>/CLAUDE.md inside a marker block

Each successful write triggers an incremental reindex through the
indexer so the new memory is immediately searchable.
"""

from __future__ import annotations

import datetime as dt
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ..config import SomniumConfig
from ..indexer import index_single_file
from ..storage.vector import VectorStore

SKIPPED_CATEGORIES_WITHOUT_PROJECT = {
    "project_memory",
    "project_skill",
    "claude_md_patch",
}

CLAUDE_MD_MARKER_START = "<!-- somnium:dream:start -->"
CLAUDE_MD_MARKER_END = "<!-- somnium:dream:end -->"


@dataclass
class WriteRecord:
    category: str
    title: str
    path: str
    status: str  # "written", "appended", "skipped", "error"
    reason: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "category": self.category,
            "title": self.title,
            "path": self.path,
            "status": self.status,
            "reason": self.reason,
        }


def _slugify(text: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9\s-]", "", text).strip().lower()
    slug = re.sub(r"[\s-]+", "-", slug)
    return slug[:60] or "item"


def _write_memory_md(
    *,
    target_dir: Path,
    title: str,
    content: str,
    category: str,
    tags: list[str] | None,
) -> Path:
    target_dir.mkdir(parents=True, exist_ok=True)
    now = dt.datetime.now()
    date_stamp = now.strftime("%Y-%m-%d")
    slug = _slugify(title)
    target = target_dir / f"{date_stamp}-{slug}.md"
    counter = 1
    while target.exists():
        target = target_dir / f"{date_stamp}-{slug}-{counter}.md"
        counter += 1

    fm_lines = [
        "---",
        f"created_at: {now.isoformat()}",
        f"category: {category}",
        "source: dream",
    ]
    if tags:
        fm_lines.append(f"tags: {json.dumps(tags)}")
    fm_lines.append("---")

    body = "\n".join(fm_lines) + "\n\n"
    if title:
        body += f"# {title}\n\n"
    body += content.strip() + "\n"
    target.write_text(body, encoding="utf-8")
    return target


def _write_skill(*, skills_dir: Path, title: str, content: str) -> Path:
    skills_dir.mkdir(parents=True, exist_ok=True)
    slug = _slugify(title)
    target_dir = skills_dir / slug
    # Auto-increment on collision to avoid overwriting a skill the user
    # has edited manually. If you want the dream to UPDATE an existing
    # skill, the dream agent should emit the same slug and we can
    # detect + overwrite in a future pass.
    counter = 1
    base_slug = slug
    while target_dir.exists():
        target_dir = skills_dir / f"{base_slug}-{counter}"
        counter += 1
    target_dir.mkdir(parents=True)
    target = target_dir / "SKILL.md"

    fm = (
        "---\n"
        f"name: {title}\n"
        f"description: (auto-generated by Somnium dream mode)\n"
        f"source: dream\n"
        "---\n\n"
    )
    target.write_text(fm + content.strip() + "\n", encoding="utf-8")
    return target


def _append_claude_md_patch(*, project_root: Path, content: str) -> Path:
    claude_md = project_root / "CLAUDE.md"
    existing = claude_md.read_text(encoding="utf-8") if claude_md.exists() else ""

    stamp = dt.datetime.now().isoformat()
    block = (
        f"\n{CLAUDE_MD_MARKER_START}\n"
        f"<!-- somnium auto-appended {stamp} -->\n"
        f"{content.strip()}\n"
        f"{CLAUDE_MD_MARKER_END}\n"
    )

    # If a marker block already exists, append inside it. Otherwise
    # append to the bottom.
    if CLAUDE_MD_MARKER_START in existing and CLAUDE_MD_MARKER_END in existing:
        # Insert new content right before the END marker.
        idx = existing.rfind(CLAUDE_MD_MARKER_END)
        new_content = (
            existing[:idx]
            + f"<!-- somnium auto-appended {stamp} -->\n{content.strip()}\n"
            + existing[idx:]
        )
    else:
        new_content = existing.rstrip() + "\n" + block

    claude_md.write_text(new_content, encoding="utf-8")
    return claude_md


def _reindex_file(path: Path, kind: str, config: SomniumConfig) -> None:
    """Upsert a single file into the right vector store. Non-fatal on error."""
    if kind in {"memory_global", "skill_global"}:
        store_path = config.global_index_path
    elif kind in {"memory_project", "skill_project"}:
        if not config.project_index_path:
            return
        store_path = config.project_index_path
    else:
        return

    try:
        with VectorStore(store_path) as store:
            index_single_file(store=store, path=path, kind=kind, config=config)
    except Exception:  # noqa: BLE001
        # Dream router must not blow up on a bad index; log elsewhere.
        pass


def dispatch(
    items: list[dict[str, Any]],
    config: SomniumConfig,
) -> list[WriteRecord]:
    """Write all items and return per-item records."""
    records: list[WriteRecord] = []

    for item in items:
        category = item.get("category", "")
        title = item.get("title", "").strip()
        content = item.get("content", "").strip()
        tags = item.get("tags") or []

        if not title or not content:
            records.append(
                WriteRecord(
                    category=category,
                    title=title,
                    path="",
                    status="skipped",
                    reason="missing title or content",
                )
            )
            continue

        # Guard: project-scoped items need a detected project root.
        if category in SKIPPED_CATEGORIES_WITHOUT_PROJECT and not config.project_root:
            records.append(
                WriteRecord(
                    category=category,
                    title=title,
                    path="",
                    status="skipped",
                    reason="no project detected",
                )
            )
            continue

        try:
            if category == "global_memory":
                path = _write_memory_md(
                    target_dir=config.global_memory_dir,
                    title=title,
                    content=content,
                    category=category,
                    tags=tags,
                )
                _reindex_file(path, "memory_global", config)
                records.append(
                    WriteRecord(category, title, str(path), "written")
                )

            elif category == "project_memory":
                assert config.project_memory_dir is not None
                path = _write_memory_md(
                    target_dir=config.project_memory_dir,
                    title=title,
                    content=content,
                    category=category,
                    tags=tags,
                )
                _reindex_file(path, "memory_project", config)
                records.append(
                    WriteRecord(category, title, str(path), "written")
                )

            elif category == "global_skill":
                path = _write_skill(
                    skills_dir=config.global_skills_dir,
                    title=title,
                    content=content,
                )
                _reindex_file(path, "skill_global", config)
                records.append(
                    WriteRecord(category, title, str(path), "written")
                )

            elif category == "project_skill":
                assert config.project_root is not None
                path = _write_skill(
                    skills_dir=config.project_root / ".claude" / "skills",
                    title=title,
                    content=content,
                )
                _reindex_file(path, "skill_project", config)
                records.append(
                    WriteRecord(category, title, str(path), "written")
                )

            elif category == "claude_md_patch":
                assert config.project_root is not None
                path = _append_claude_md_patch(
                    project_root=config.project_root,
                    content=content,
                )
                records.append(
                    WriteRecord(category, title, str(path), "appended")
                )

            else:
                records.append(
                    WriteRecord(
                        category=category,
                        title=title,
                        path="",
                        status="skipped",
                        reason=f"unknown category: {category!r}",
                    )
                )

        except Exception as exc:  # noqa: BLE001
            records.append(
                WriteRecord(
                    category=category,
                    title=title,
                    path="",
                    status="error",
                    reason=str(exc),
                )
            )

    return records
